name: release-please

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: go
          bump-minor-pre-major: true
